language: node_js
node_js:
- stable
deploy:
  api_key:
    secure: NEAknYkMwEfEXu4YVJjpx7YQcU2uiPViNSVXemBq8Aa8OzigUGpJpHdIgGzF0fEwAfqd6i4Ig3snSA2ItJ6jMbcmZgOJ/K7jnRTvKfwhdfpyQDuqW3E0h5Jb6MOaEntLwejkE4+tC+stKTshxhATD4UFr09zui9QZ9aSruXCS86xJ7ExES7pWho+oglNtRHkBEEI5XdvKLtfyEtqBVGg1OyBcv9uTIFfu3MVJelj4T3AGrWvxM1duaQ7wKwIq+aRm+PzWR+Ht4ofH2vdRoDeS8dD9MWK00P5RPdlwcXCMNYQew/vF8zLvu2kXhnxOYkgb5+xqeTawyeyj5h2kgIk6Y4Wyx/KjEEo45sM49bViWQIcZajJ0PrnAjVhCirbCjXjQgdKe/ZOIM9AT9y0m071B+tNsPC5kIcMmORx8XBRCHOhK4LrrZm7cCRh6V6OBf5qzEeTD9LMM7wtOAJzsDVrJfN4hGIUmNMMnUgVPxj9ro1T1e2vkW8b3u8Vn5j6oO7AdCzNuySAMEPNlaGPXlg6qApltZYK7rc4NKczPKt9hvwasBPr722DA3tFCLAGZlLdZNHKCckpGqtmv6UYCRFVtYVVDGWogdAjD98FS91oN59JZqNw8tg/Dgw/LZeW+jbuYvhAHxE6wbaKQEGQfRuRGhvBHDN/TkBHcftUU+yOXU=
  provider: heroku
  strategy: api
  on:
    all_branches: false
  app:
    master: harvest-api-staging
    production: harvest-api-production
    develop: harvest-api-dev
