language: node_js
node_js:
- stable
deploy:
  api_key:
    secure: G2orMf6DDoLast+mD8KlZfpt9zwKYGx+NhlZmtnKatvd6nbhYXS2V5A3AOLEvp6RoIC+pMRmVZiRbL4JmQGIilB2TsJS4nPS+UFVQJhYCBskpgCpTV5njCsgdk3Wyup8RRYEpzkvuK729htFYQYXCLnEP9fFGVt0gMCqWQwFN85VWhD/7Hwgot0PkOMKIacrUtnfwYE4ipjBFGy/enZoddKHFtGCMzkM5QQ4AVmvZjdpkBNLQzVZui1cokqZ/0NDGBgA3lGSBYAcjh9s+SbYsYQJjX09Tqr6uI6rhLVQ23ExcmErAXvQUN+qbcU5irMsr0UAWFjnIA+ouGQor9VzBdXmKguK/1dluVqzT/7kJzWJ3eApaEMltqKRFjNKksU2EUQAp4+0AGC86j95/rmpdGg0wJtvXCOs4tovd4BYfN71M1Fi+3mWjjlRkTGijuEGNduUtdaPXuOkfO8wgM2x+V77JO4VWSOkAlWl48FqnYlcXUg3qbe47GJ6dXXSmJLGmCQnZK5pYf52oQLbkvqiaJuf+mFBr0SZvlFNmeTbFt6Wc4HB0lZxPBZi2BJkJpKv4mA9rer87OhZUcpb4rBeJWMPvw1pWIQ+axwH7dVSiU9j1HWFlWczfhgH575ZVLHP9BFNUtWKPLzNG1SAbn/l9W/C7k2KKj0LSciKlI7MqWM=
  provider: heroku
  strategy: api
  on:
    all_branches: false
  app:
    master: harvest-api-staging
    production: harvest-api-production
    develop: harvest-api-dev
