# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: HarvestAPI
  description: Open Data + Agriculture 
  version: "0.0.0"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
# the domain of the service
host: localhost:3000
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/
tags:
  - name: Farmer
    description: Farmer information
  - name: Property
    description: Property information
  - name: Livestock
    description: Livestock information
  - name: Crop
    description: Crop information
paths:
  /farmers:
    get: 
      summary: Get All Farmers
      description: |
       Retrieve information on all farmers
      operationId: getAllFarmers
      tags:
        - Farmer
      produces:
        - application/json
      responses:
        default:
          description: Bad request
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Message'
          examples:
            'application/json':
              message: 'imagine getFarmerByID x 50!'
  /farmers/{id}:
    get:
      summary: Get Farmer By ID
      description: |
       Retrieve information on a farmer, provided an ID
      operationId: getFarmerByID
      tags:
        - Farmer
        - Resource
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: requests object
          type: string
          required: true
      responses:
        default:
          description: Bad request
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Message'
          examples:
            'application/json':
                IDX_StakeHolder:
                    type: array
                    message: [952520,952520]
                StakeHolder_Num:
                    type: string
                    message: '081117655'
                Stakeholder_Type_Code:
                    type: integer
                    message: 1
                Company_Name:
                    type: string
                    message: 
                First_Name:
                    type: string
                    message: 'ERROL'
                Middle_Name:
                    type: string
                    message: 'CHARLES'
                Last_Name:
                    type: string
                    message: 'LENNOX'
                Alias:
                    type: string
                    message: 
                DOB:
                    type: string
                    message: '1975-11-30T00:00:00.000Z'
                Gender:
                    type: integer
                    message: 1
                Jas_Receipt:
                    type: string
                    message: '0'
                Res_Street_Address:
                    type: string
                    message: 'MERTON PEN'
                Res_District_Name:
                    type: string
                    message: 'GRANGE HILL'
                Res_Post_Office:
                    type: string
                    message: 'Grange Hill P.A.'
                Res_Parish_Code:
                    type: integer
                    message: 4
                Res_Tele_Num:
                    type: string
                    message: '457-8027'
                Bus_Street_Address:
                    type: string
                    message: 
                Bus_District_Name:
                    type: string
                    message: 'GRANGE HILL'
                Bus_Post_Office:
                    type: string
                    message: 
                Bus_Parish_Code:
                    type: integer
                    message: 4
                Bus_Tele_Num:
                    type: integer
                    message: 
                Cell_Num:
                    type: string
                    message: 
                Email_Address:
                    type: string
                    message: 
                Fax_Num:
                    type: string
                    message: 
                Identification_Num:
                    type: string
                    message: '106699920'
                ID_Type_Code:
                    type: integer
                    message: 3
                TRN:
                    type: string
                    message: '106699920'
                Interviewer:
                    type: string
                    message: null
                Stakeholder_Status_Code:
                    type: integer
                    message: 1
                Verified_Status:
                    type: integer
                    message: 1
                Verified_Date:
                    type: string
                    message: '2009-01-09T00:00:00.000Z'
                Registration_Date:
                    type: string
                    message: '2008-10-17T00:00:00.000Z'
                Have_Photo_YN:
                    type: integer
                    message: 0
                Want_Photo_ID_YN:
                    type: integer
                    message: 1
                Photo_Path:
                    type: string
                    message: '081117655.jpg'
                Photo_ID_Upload_Date:
                    type: string
                    message: null
                Photo_Found_YN:
                    type: string
                    message: null
                IDX_EOJ_Photo_Batch:
                    type: string
                    message: null
                Photo_Status:
                    type: integer
                    message: 1
                Old_Photo_ID_Printed_YN:
                    type: string
                    message: null
                Old_Photo_Path:
                    type: string
                    message: null
                Old_Photo_Print_Date:
                    type: string
                    message: null
                Old_Have_Photo_YN:
                    type: string
                    message: null
                Create_Date:
                    type: array
                    message: ['2008-11-03T08:50:30.900Z','2008-11-03T08:51:59.590Z']
                Update_Date:
                    type: array
                    message: ['2009-01-09T00:00:00.000Z','2008-11-03T08:51:59.590Z']
                ReVerified_Date:
                    type: string
                    message: null
                ReVerified_Status:
                    type: string
                    message: null
                tracker_farmer_yn:
                    type: integer
                    message: 0
                Title:
                    type: string
                    message: null
                Stakeholder_Status_Date:
                    type: string
                    message: null
                primary_parish:
                    type: integer
                    message: 4
                primary_extension_area:
                    type: integer
                    message: 9
                primary_district:
                    type: integer
                    message: 994
                Update_By:
                    type: integer
                    message: null
                tracker_group:
                    type: string
                    message: null
                tracker_start_date:
                    type: string
                    message: null
                IDX_Farmer_Profile:
                    type: integer
                    message: 523402
                Respondent_Code:
                    type: integer
                    message: 1
                Manager_Code:
                    type: integer
                    message: 1
                Live_On_Farm_YN:
                    type: integer
                    message: 1
                Income_Source_Code:
                    type: integer
                    message: 1
                Education_Level_Code:
                    type: integer
                    message: 5
                Occupation_Code:
                    type: integer
                    message: 7
                Agri_Training_YN:
                    type: integer
                    message: 2
                Farmer_Type_Code:
                    type: integer
                    message: 1
                Training_Method_Code:
                    type: integer
                    message: null
                Agri_Institution_Code:
                    type: integer
                    message: null
                Qualification_Code:
                    type: integer
                    message: 3
                Holding_Start:
                    type: string
                    message: '1994'
                Main_Agri_Activity_Code:
                    type: integer
                    message: 2
                Nearest_Police_Station:
                    type: string
                    message: 'Manchioneal'
                Farmer_Profile_Remarks:
                    type: string
                    message: null
                Jas_Farmer_Group:
                    type: string
                    message: 
                House_Hold_No:
                    type: string
                    message: null
definitions:
  Message:
    required:
      - message
    properties:
      message:
        type: string
        default: 'Hello, Adam!'
